// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isbvypyvnyeeezpompdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzYnZ5cHl2bnllZWV6cG9tcGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTYzMzgsImV4cCI6MjA2NjQzMjMzOH0.DMVWaIE8H3Bpnm4YSyHiRDW_41GsH-nzq79Rx0FcSSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);